[package]
name = "pyth-oracle"
version = "2.13.1"
edition = "2021"
license = "Apache 2.0"
publish = false

[build-dependencies]
bindgen = "0.60.1"

[dependencies]
solana-program = "=1.13.3"
bytemuck = "1.11.0"
thiserror = "1.0"

[dev-dependencies]
solana-program-test = "=1.13.3"
solana-sdk = "=1.13.3"
tokio = "1.14.1"

[features]
debug = []

[lib]
crate-type = ["cdylib", "lib"]
