name: Rust CI Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  rust-ci-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
    - uses: pre-commit/action@v2.0.3
    - name: Build
      run: RUSTFLAGS="-D warnings" cargo build
    - name: Test
      run: |
         cargo test
         cargo test-bpf
